version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=<your-mongodb-uri>
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

